### ISSUE TITLE
1 to M matching

### ISSUE THREAD

**Issue by luca-merlo** [cran/CausalGPS#2]
Hi @Naeemkh,
In our project with Xiao we had to implement 1 to M matching starting from GPS matching. To do this in R, I used the `which.minn` function in the "doBy" package by modifying the original R code of Xiao. 
I am wondering if this could be a useful feature to add to the "CausalGPS" package even though the `compute_closest_wgps` function is now implemented in c++. 

Thanks,
Luca

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
